CREATE TABLE dbo.Users (
    UserID INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Email NVARCHAR(255) NOT NULL UNIQUE,
    Password NVARCHAR(255) NOT NULL,
    DOB NVARCHAR(25) NOT NULL,
    Gender NVARCHAR(25) NOT NULL,
    Address NVARCHAR(255) NOT NULL
);

CREATE TABLE dbo.Appointments (
    AppointmentID INT IDENTITY(1,1) PRIMARY KEY,
    Email NVARCHAR(255) NOT NULL,
    [Date] NVARCHAR(20) NOT NULL,
    [Time] NVARCHAR(20) NOT NULL,
    Reason NVARCHAR(255) NOT NULL,
    Hospital NVARCHAR(255) NOT NULL,
    FullName NVARCHAR(100) NOT NULL,
    DOB NVARCHAR(20) NOT NULL,
    NHUKNumber NVARCHAR(20) NULL
);

ALTER TABLE dbo.Appointments
ADD CONSTRAINT UQ_AppointmentSlot
UNIQUE ([Date], [Time], Hospital);